name: Publish to stable

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-24.04
    environment: production
    timeout-minutes: 60

    steps:
      - name: Install snapcraft
        run: sudo snap install snapcraft --classic

      - name: Promote edge to stable
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        run: snapcraft promote bottom --from-channel edge --to-channel stable --yes
