name: Publish snap
on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release channel"
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - edge

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: ClementTsang/action-build@a9eaaaf04e8b0ab0bdb6a2f924206987e3ff4833
        id: build

      - uses: ClementTsang/action-publish@d568998a48cc6f18958ac2b08f7528ea1de568fa
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ github.event.inputs.release }}
